version: 2.1

orbs:
  codacy: codacy/base@12.1.5
  codacy_plugins_test: codacy/plugins-test@2.0.11

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "set scalafmtUseIvy in ThisBuild := false;
                 scalafmt::test;
                 test:scalafmt::test;
                 sbt:scalafmt::test;
                 set version in Docker := \"latest\";
                 universal:stage"
            docker build -t $CIRCLE_PROJECT_REPONAME .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
